#!/bin/bash -l
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH -n 4
#SBATCH -c 2
#SBATCH --gres=gpu:4
#SBATCH --mem=32000
#SBATCH -J tera
#SBATCH -t 7-00:00:00

#SBATCH --no-requeue

# Record job info
echo -e "$SLURM_JOB_ID  $HOSTNAME  $(pwd)" >> ~/.myslurmhistory

module load intel cuda/9.0
export CUDA_CACHE_PATH=/scratch/$USER/.nv/ComputeCache
export TeraChem=/home/leeping/opt/terachem/current
export PATH=$TeraChem/bin:$PATH
export LD_LIBRARY_PATH=$TeraChem/lib:$LD_LIBRARY_PATH


terachem  run.in &> run.out

na=$(head -1 scr/optim.xyz) && tail -$((na+2)) scr/optim.xyz > end.xyz